### ISSUE TITLE
Cloud and mountain generation

### ISSUE THREAD

**Issue by engboris** [eikofee/nene-quest#7]
I'm not sure if the `Background` class should be responsible for the generation of clouds and mountains.

* What do you think about a class `CloudGenerator` and `MountainGenerator` ? Both would be used by `Background`.
* I think we should rename `RandomCloud` to `Cloud` because it really is a cloud and nothing more (same for mountains). 
* Moreover, I think it would be wise to have a superclass `Generator`. We can see some factorizable duplications in the code : 
```cpp
void Background::update() {
	for (int i = 0; i < this->clouds.size(); i++) {
		bool active = this->clouds.at(i)->isAlive();
		if (active) {
			this->clouds.at(i)->translate(- (scrollSpeed + 1) * cloudSpeedModifier, 0);
			this->clouds.at(i)->update();
		}
		else {
			delete(this->clouds.at(i));
			this->clouds.erase(this->clouds.begin() + i);
			i--;
		}
	}

	for (int i = 0; i < this->mountains.size(); i++) {
		bool active = this->mountains.at(i)->isAlive();
		if (active) {
			this->mountains.at(i)->translate(- scrollSpeed * mountainSpeedModifier, 0);
			this->mountains.at(i)->update();
		}
		else {
			delete(this->mountains.at(i));
			this->mountains.erase(this->mountains.begin() + i);
			i--;
		}
	}

	this->createClouds();
	this->createMountains();
}
```

`Cloud` should be an "abstract cloud" without any reference to any constant "size", "height" or "angle".  Then we define all the constant parameters in the "generators". That's what I suggest to unify all the parameters.

**Comment by Echoffee** [comment]
Yeah, I was thinking about factoring a bit of this part, but I didn't really thought about it. Moreover, I don't think it's a huge issue at this current state.

That's another thing to put on our backlog I guess 🤔

**Comment by engboris** [comment]
Has the problem been solved ?

**Comment by eikofee** [comment]
no idea
